config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index', as: '/'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }, :skip => [:registrations]


  namespace :backoffice do
    get '/admin', to: 'dashboard#index'
    resources :users
    resources :items
    resources :time_charts
    resources :inventory_items
    resources :categories
    resources :report_lists
    resources :lost_items
    get '/inventory_list', to: 'inventory_items#inventory_list'
    get 'compare_charts', to: 'time_charts#chart_new'
    post 'compare_charts', to: 'time_charts#chart_create'
    get '/items_list', to: 'items#items_list'
    put '/sell_item', to: 'items#sell'
    patch '/update_lost_item', to: 'items#lost_item'
    get '/sold_list', to: 'sold_items#index'
  end

end

app/models/backoffice/report_list.rb
class Backoffice::ReportList < ApplicationRecord
end

app/models/inventory_item.rb
class InventoryItem < ApplicationRecord
  validates :code, uniqueness: true
  has_many :inventory_categories
  has_many :categories, through: :inventory_categories
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.json { render json: CategoryDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to backoffice_categories_path, notice: 'Categoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to backoffice_categories_path, notice: 'Categoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_categories_path, notice: 'Categoria deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:id, :name)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = Item.all
    soldItems = SoldItem.all
    lostItems = LostItem.all
    @total_amount =0
    @total_value =0
    @sold_value = 0.0
    @sold_amount = 0
    @lost_value = 0.0
    @lost_amount = 0
    @items.each do |item|
      @total_amount += item.amount
      @total_value += item.value.to_f * item.amount.to_i
    end
    soldItems.each do |soldItem|
      @sold_value += soldItem.value
      @sold_amount += soldItem.amount
    end
    lostItems.each do |lostItem|
      @lost_value += lostItem.value
      @lost_amount += 1
    end
  end
end

app/controllers/backoffice/inventory_items_controller.rb
class Backoffice::InventoryItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_inventory_item, only: [:show, :edit, :update, :destroy]

  # GET /inventory_items
  # GET /inventory_items.json
  def index
    @inventory_items = InventoryItem.all
    @total_amount = 0
    @total_current_value = 0.0
    @total_value = 0.0
    @inventory_items.each do |inventory_item|
      @total_amount += 1
      @total_current_value += inventory_item.current_value
      @total_value += inventory_item.value
    end
  end

  # GET /inventory_list
  def inventory_list
    @inventory_items = InventoryItem.all.order('updated_at DESC')
    respond_to do |format|
      format.html
      format.json { render json: InventoryItemDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /inventory_items/1
  # GET /inventory_items/1.json
  def show
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items
  # POST /inventory_items.json
  def create
    @inventory_item = InventoryItem.new(inventory_item_params)
    puts(params)

    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to backoffice_inventory_list_path, notice: 'Bem de patrimônio criado com sucesso.' }
        format.json { render :show, status: :created, location: @inventory_item }
      else
        format.html { render :new, notice: 'Algo de errado aconteceu.' }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1
  # PATCH/PUT /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to backoffice_inventory_list_path, notice: 'Bem de patrimônio atualizado com sucesso.'}
        format.json { render :show, status: :ok, location: @inventory_item }
      else
        format.html { render :edit, notice: 'Algo de errado aconteceu.' }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  # DELETE /inventory_items/1.json
  def destroy
    @inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_inventory_list_path, notice: 'Bem de patrimônio deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_inventory_item
    @inventory_item = InventoryItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def inventory_item_params
    params.require(:inventory_item).permit(:id, :name, :code, :responsible,
                                           :area, :acquisition_mode, :conservation_state,
                                           :serial_number, :model,
                                           :storage_location, :age,
                                           :value, :lifespan, :current_value,
                                           :date_of_acquisition, :depreciation,
                                           :category_ids)
  end
end

app/controllers/backoffice/items_controller.rb
# frozen_string_literal: true

class Backoffice::ItemsController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = Item.all
    @total_value = 0.0
    @total_amount =0
    @value_sold = 0.0
    @total_sold =0
    @items.each do |item|
      @total_amount += item.amount
      @total_value += item.value.to_f * item.amount.to_i
      @value_sold += item.value_sold.to_f
      @total_sold += item.total_sold.to_i
    end
  end

  def sell
    @item = Item.find(params[:id])
    addToSold(@item)
    @item.amount = @item.amount - 1
    @item.total_sold = @item.total_sold + 1
    @item.value_sold = @item.value_sold +  @item.value
    if @item.amount == 0
      @item.destroy
    else
      @item.save
    end
    respond_to do |format|
      format.html { redirect_to backoffice_items_list_path, notice: 'Quantidade do item diminuida.'}
      format.js {  }
    end
  end

  def lost_item
    @item = Item.find(params[:item_id])
    lost_amount = params[:item][:amount].to_i
    if params[:item] and params[:item][:amount]
      iterator = 0
      until iterator >= lost_amount
        addToLost(@item, params[:lost_status])
        iterator = iterator + 1
      end
    end
    @item.amount = @item.amount - params[:item][:amount].to_i
    if @item.amount == 0
      @item.destroy
    else
      @item.save
    end
    respond_to do |format|
      format.html { redirect_to backoffice_items_list_path, notice: 'Quantidade do item diminuida.'}
      format.js { }
    end
  end

  # GET /items_list
  def items_list
    @items = Item.all.order('updated_at DESC')
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, view_context: view_context) }
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to backoffice_items_path, notice: 'Item foi criado com sucesso.' }
        format.js { }
      else
        format.html { render :new, notice: "Ocorreu um erro. Por favor, preencha todos os campos do formulário." }
        format.js {  }
      end
    end
  end

  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update(item_params_edit)
        format.html { redirect_to backoffice_items_list_path, notice: "Item foi atualizado com sucesso." }
        format.js { }
      else
        format.html { render :edit, notice: "Ocorreu um erro. Por favor, preencha todos os campos do formulário." }
        format.js {  }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_items_path, notice: 'Doação deletada com sucesso.' }
      format.js {}
    end
  end

  private
  def addToSold(item)
    soldItem = SoldItem.new
    soldItem.name = item.name
    soldItem.code = item.id
    soldItem.value = item.value
    soldItem.amount = 1
    soldItem.save
  end

  def addToLost(item, status)
    lostItem = LostItem.new
    lostItem.name = item.name
    lostItem.code = item.id
    lostItem.value = item.value
    lostItem.status = status
    lostItem.save
  end

  def item_params
    params.require(:item).permit(:id, :name, :observation, :amount, :value,
                                 :donor, :receiver, :internal, :used, :lost,
                                 :used_product, :new_product)
  end
  def item_params_edit
    params.require(:item).permit(:id, :name, :observation, :amount, :value,
                                 :donor, :receiver, :internal, :used, :lost,
                                 :used_product, :new_product, :created_at)
  end
end

app/controllers/backoffice/lost_items_controller.rb
class Backoffice::LostItemsController < ApplicationController
  before_action :set_lost_item, only: [:show, :edit, :update, :destroy]

  # GET /lost_items
  # GET /lost_items.json
  def index
    @lost_items = LostItem.all.order('updated_at DESC')
    respond_to do |format|
      format.html
      format.json { render json: LostItemDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /lost_items/1
  # GET /lost_items/1.json
  def show
  end

  # GET /lost_items/new
  def new
    @lost_item = LostItem.new
  end

  # GET /lost_items/1/edit
  def edit
  end

  # POST /lost_items
  # POST /lost_items.json
  def create
    @lost_item = LostItem.new(lost_item_params)

    respond_to do |format|
      if @lost_item.save
        format.html { redirect_to @lost_item, notice: 'Lost item was successfully created.' }
        format.json { render :show, status: :created, location: @lost_item }
      else
        format.html { render :new }
        format.json { render json: @lost_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lost_items/1
  # PATCH/PUT /lost_items/1.json
  def update
    respond_to do |format|
      if @lost_item.update(lost_item_params)
        format.html { redirect_to @lost_item, notice: 'Lost item was successfully updated.' }
        format.json { render :show, status: :ok, location: @lost_item }
      else
        format.html { render :edit }
        format.json { render json: @lost_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lost_items/1
  # DELETE /lost_items/1.json
  def destroy
    @lost_item.destroy
    respond_to do |format|
      format.html { redirect_to lost_items_url, notice: 'Lost item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lost_item
      @lost_item = LostItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lost_item_params
      params.require(:lost_item).permit(:name, :code, :value, :status)
    end
end

app/controllers/backoffice/sold_items_controller.rb
class Backoffice::SoldItemsController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json { render json: SoldItemDatatable.new(params, view_context: view_context) }
    end
  end
end

app/helpers/backoffice/report_lists_helper.rb
module Backoffice::ReportListsHelper
end

app/helpers/backoffice/sold_items_helper.rb
module Backoffice::SoldItemsHelper
end

app/helpers/inventory_items_helper.rb
module InventoryItemsHelper
end

app/views/backoffice/inventory_items/edit.html.erb
<h1>Editar bem de patrimônio</h1>

<%= render 'form', inventory_item: @inventory_item %>

app/views/backoffice/inventory_items/index.html.erb
<h1>Inventário de bens patrimôniais</h1>
<div class="row purchace-popup">
  <div class="col-12">
    <span class="d-block d-md-flex align-items-center">
      <%= link_to "/backoffice/inventory_items/new", class: "btn btn-success btn-lg btn-fw" do %>
        <i class="mdi mdi-plus-circle" style="color: white"></i>
        <span class="menu-title">Novo bem</span>
      <% end %>
      <%= link_to "/backoffice/inventory_list", class: "btn btn-primary btn-lg btn-fw" do %>
              <i class="mdi mdi-view-list" style="color: white"></i>
              <span class="menu-title">Listagem de bens</span>
            <% end %>
    </span>
  </div>
</div>
<div class="row">
  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <i class="mdi mdi-file-document-box text-danger icon-lg"></i>
          </div>
          <div class="float-right">
            <p class="mb-0 text-right">Total de bens de patrimônio</p>
            <div class="fluid-container">
              <h3 class="font-weight-medium text-right mb-0"><%= @total_amount %> itens</h3>
            </div>
          </div>
        </div>
        <p class="text-muted mt-3 mb-0">
          <i class="mdi mdi-alert-octagon mr-1" aria-hidden="true"></i> Ultima item adicionado em:
          <% if @inventory_items.last %>
            <%= @inventory_items.last.created_at.strftime("%d/%m/%Y") %>
          <% else %>
            Nenhum item cadastrado.
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <i class="mdi mdi-coin text-warning icon-lg"></i>
          </div>
          <div class="float-right">
            <p class="mb-0 text-right">Valor total dos bens de patrimônio</p>
            <div class="fluid-container">
              <h3 class="font-weight-medium text-right mb-0"><%= number_to_currency(@total_value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></h3>
            </div>
          </div>
        </div>
        <p class="text-muted mt-3 mb-0">
          <i class="mdi mdi-bookmark-outline mr-1" aria-hidden="true"></i> Considerando apenas os valores no recebimento
        </p>
      </div>
    </div>
  </div>
  <div class="col-xl-3 col-lg-3 col-md-3 col-sm-6 grid-margin stretch-card">
    <div class="card card-statistics">
      <div class="card-body">
        <div class="clearfix">
          <div class="float-left">
            <i class="mdi mdi-coin text-warning icon-lg"></i>
          </div>
          <div class="float-right">
            <p class="mb-0 text-right">Valor total atual dos bens de patrimônio</p>
            <div class="fluid-container">
              <h3 class="font-weight-medium text-right mb-0"><%= number_to_currency(@total_current_value, :unit => "R$ ", :separator => ",", :delimiter => ".") %></h3>
            </div>
          </div>
        </div>
        <p class="text-muted mt-3 mb-0">
          <i class="mdi mdi-bookmark-outline mr-1" aria-hidden="true"></i> Considerando apenas os valores atuais.
        </p>
      </div>
    </div>
  </div>
</div>

app/views/backoffice/inventory_items/inventory_list.html.erb
<div class="row purchace-popup">
  <div class="col-12">
    <span class="d-block d-md-flex align-items-center">
      <%= link_to "/backoffice/inventory_items/new", class: "btn btn-success btn-lg btn-fw" do %>
        <i class="mdi mdi-plus-circle" style="color: white"></i>
        <span class="menu-title">Novo bem</span>
      <% end %>
      <%= link_to "/backoffice/inventory_items", class: "btn btn-primary btn-lg btn-fw" do %>
              <i class="mdi mdi-view-list" style="color: white"></i>
              <span class="menu-title">Painel inicial</span>
            <% end %>
    </span>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h4 class="card-title">Listagem completa bens de patrimônio</h4>
    <div class="table-responsive" style="overflow-y: auto;">
      <table class="table table-striped Flipped" id="inventory-items-datatable" data-source="<%= backoffice_inventory_list_path(format: :json) %>">
        <thead>
        <tr>
          <th>
            Nome do item
          </th>
          <th>
            Código
          </th>
          <th>
            Valor
          </th>
          <th>
            Modelo
          </th>
          <th>
            Data de aquisição
          </th>
          <th>
            Informações
          </th>
          <th>
            Editar
          </th>
          <th>
            Deletar
          </th>
        </tr>
        </thead>
        <tbody>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script charset="utf-8">
    jQuery(document).ready(function() {
        $('#inventory-items-datatable').dataTable({
            "processing": true,
            "serverSide": true,
            "ajax": $('#inventory-items-datatable').data('source'),
            "pagingType": "full_numbers",
            "oLanguage": {
                "sEmptyTable": "Nenhum registro encontrado",
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "_MENU_ resultados por página",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sZeroRecords": "Nenhum registro encontrado",
                "sSearch": "Pesquisar",
                "oPaginate": {
                    "sNext": "Próximo",
                    "sPrevious": "Anterior",
                    "sFirst": "Primeiro",
                    "sLast": "Último"
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            },
            "columns": [
                {"data": "name"},
                {
                    "data": "code"
                },
                {
                    "data": "value"
                },
                {
                    "data": "model"
                },
                {
                    "data": "date_of_acquisition",
                    "type": "date",
                    "render": function (data) {
                        var date = new Date(data);
                        var month = date.getMonth() + 1;
                        return ( date.getDate() + "/" + ((month >= 10) ? month : "0" + month) + "/" + date.getFullYear());
                    }
                },
                {
                    "data": "information",
                    "bSortable": false,
                },
                {
                    "data": "edit",
                    "bSortable": false,
                },
                {
                    "data": "delete",
                    "bSortable": false,
                },
            ]
        });
    });
</script>

app/views/backoffice/inventory_items/new.html.erb
<h1>Novo bem de patrimônio</h1>

<%= render 'form', inventory_item: @inventory_item %>

app/views/backoffice/inventory_items/show.html.erb
<div class="row purchace-popup">
  <div class="col-12">
    <span class="d-block d-md-flex align-items-center">
      <%= link_to "/backoffice/inventory_items/new", class: "btn btn-success btn-lg btn-fw" do %>
        <i class="mdi mdi-plus-circle" style="color: white"></i>
        <span class="menu-title">Novo bem</span>
      <% end %>
      <%= link_to "/backoffice/inventory_list", class: "btn btn-primary btn-lg btn-fw" do %>
              <i class="mdi mdi-view-list" style="color: white"></i>
              <span class="menu-title">Listagem de bens</span>
            <% end %>
    </span>
  </div>
</div>
<div class="card">
  <div class="card-body">
    <h2><%= @inventory_item.name %></h2>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>
            Nome
          </th>
          <th>
            Código
          </th>
          <th>
            Categoria
          </th>
          <th>
            Responsável
          </th>
          <th>
            Área
          </th>
          <th>
            Estado de conservação
          </th>
          <th>
            Data de aquisição
          </th>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td class="py-1">
            <%= @inventory_item.name %>
          </td>
          <td>
            <%= @inventory_item.code %>
          </td>
          <td>
            <%= @inventory_item.categories[0].name %>
          </td>
          <td>
            <%= @inventory_item.responsible %>
          </td>
          <td>
            <%= @inventory_item.area %>
          </td>
          <td>
            <%= @inventory_item.conservation_state %>
          </td>
          <td>
            <% if @inventory_item.date_of_acquisition %>
              <%= @inventory_item.date_of_acquisition.strftime("%d/%m/%Y") %>
            <% else %>
              Não informado
            <% end %>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
          <h3>Local de armazenamento</h3>
          <p>
            <%= @inventory_item.storage_location %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
          <h3>Forma de aquisição</h3>
          <p>
            <%= @inventory_item.acquisition_mode %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
          <h3>Valor em R$</h3>
          <p>
            <%= number_to_currency(@inventory_item.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
          <h3>Valor atual em R$</h3>
          <p>
            <%= number_to_currency(@inventory_item.current_value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
          <h3>Depreciação em R$</h3>
          <p>
            <%= number_to_currency(@inventory_item.depreciation, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
          <h3>Idade em meses</h3>
          <p>
            <%= @inventory_item.age %> mês(meses)
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
          <h3>Vida útil em anos</h3>
          <p>
            <%= @inventory_item.lifespan %> ano(s)
          </p>
        </div>
      </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 grid-margin stretch-card">
      <div class="card card-statistics">
        <div class="card-body">
        </div>
      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-body">
      <div class="form-group">
        <%= link_to 'Editar', "/backoffice/inventory_items/#{@inventory_item.id}/edit", class: 'btn btn-primary rounded' %>
        <%= link_to 'Voltar', backoffice_inventory_items_path, class: 'btn btn-primary rounded' %>
      </div>
    </div>
  </div>

</div>