config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#index', as: '/'

  devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations'
  }, :skip => [:registrations]


  namespace :backoffice do
    get '/admin', to: 'dashboard#index'
    resources :users
    resources :items
    resources :time_charts
    resources :inventory_items
    resources :categories
    resources :report_lists
    resources :lost_items
    get '/inventory_list', to: 'inventory_items#inventory_list'
    get 'compare_charts', to: 'time_charts#chart_new'
    post 'compare_charts', to: 'time_charts#chart_create'
    get '/items_list', to: 'items#items_list'
    put '/sell_item', to: 'items#sell'
    patch '/update_lost_item', to: 'items#lost_item'
    get '/sold_list', to: 'sold_items#index'
  end

end

app/models/backoffice/report_list.rb
class Backoffice::ReportList < ApplicationRecord
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
    respond_to do |format|
      format.html
      format.json { render json: CategoryDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to backoffice_categories_path, notice: 'Categoria criada com sucesso.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to backoffice_categories_path, notice: 'Categoria atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_categories_path, notice: 'Categoria deletada com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:id, :name)
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = Item.all
    soldItems = SoldItem.all
    lostItems = LostItem.all
    @total_amount =0
    @total_value =0
    @sold_value = 0.0
    @sold_amount = 0
    @lost_value = 0.0
    @lost_amount = 0
    @items.each do |item|
      @total_amount += item.amount
      @total_value += item.value.to_f * item.amount.to_i
    end
    soldItems.each do |soldItem|
      @sold_value += soldItem.value
      @sold_amount += soldItem.amount
    end
    lostItems.each do |lostItem|
      @lost_value += lostItem.value
      @lost_amount += 1
    end
  end
end

app/controllers/backoffice/inventory_items_controller.rb
class Backoffice::InventoryItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_inventory_item, only: [:show, :edit, :update, :destroy]

  # GET /inventory_items
  # GET /inventory_items.json
  def index
    @inventory_items = InventoryItem.all
    @total_amount = 0
    @total_current_value = 0.0
    @total_value = 0.0
    @inventory_items.each do |inventory_item|
      @total_amount += 1
      @total_current_value += inventory_item.current_value
      @total_value += inventory_item.value
    end
  end

  # GET /inventory_list
  def inventory_list
    @inventory_items = InventoryItem.all.order('updated_at DESC')
    respond_to do |format|
      format.html
      format.json { render json: InventoryItemDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /inventory_items/1
  # GET /inventory_items/1.json
  def show
  end

  # GET /inventory_items/new
  def new
    @inventory_item = InventoryItem.new
  end

  # GET /inventory_items/1/edit
  def edit
  end

  # POST /inventory_items
  # POST /inventory_items.json
  def create
    @inventory_item = InventoryItem.new(inventory_item_params)
    puts(params)

    respond_to do |format|
      if @inventory_item.save
        format.html { redirect_to backoffice_inventory_list_path, notice: 'Bem de patrimônio criado com sucesso.' }
        format.json { render :show, status: :created, location: @inventory_item }
      else
        format.html { render :new, notice: 'Algo de errado aconteceu.' }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inventory_items/1
  # PATCH/PUT /inventory_items/1.json
  def update
    respond_to do |format|
      if @inventory_item.update(inventory_item_params)
        format.html { redirect_to backoffice_inventory_list_path, notice: 'Bem de patrimônio atualizado com sucesso.'}
        format.json { render :show, status: :ok, location: @inventory_item }
      else
        format.html { render :edit, notice: 'Algo de errado aconteceu.' }
        format.json { render json: @inventory_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inventory_items/1
  # DELETE /inventory_items/1.json
  def destroy
    @inventory_item.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_inventory_list_path, notice: 'Bem de patrimônio deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_inventory_item
    @inventory_item = InventoryItem.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def inventory_item_params
    params.require(:inventory_item).permit(:id, :name, :code, :responsible,
                                           :area, :acquisition_mode, :conservation_state,
                                           :serial_number, :model,
                                           :storage_location, :age,
                                           :value, :lifespan, :current_value,
                                           :date_of_acquisition, :depreciation,
                                           :category_ids)
  end
end

app/controllers/backoffice/items_controller.rb
# frozen_string_literal: true

class Backoffice::ItemsController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = Item.all
    @total_value = 0.0
    @total_amount =0
    @value_sold = 0.0
    @total_sold =0
    @items.each do |item|
      @total_amount += item.amount
      @total_value += item.value.to_f * item.amount.to_i
      @value_sold += item.value_sold.to_f
      @total_sold += item.total_sold.to_i
    end
  end

  def sell
    @item = Item.find(params[:id])
    addToSold(@item)
    @item.amount = @item.amount - 1
    @item.total_sold = @item.total_sold + 1
    @item.value_sold = @item.value_sold +  @item.value
    if @item.amount == 0
      @item.destroy
    else
      @item.save
    end
    respond_to do |format|
      format.html { redirect_to backoffice_items_list_path, notice: 'Quantidade do item diminuida.'}
      format.js {  }
    end
  end

  def lost_item
    @item = Item.find(params[:item_id])
    lost_amount = params[:item][:amount].to_i
    if params[:item] and params[:item][:amount]
      iterator = 0
      until iterator >= lost_amount
        addToLost(@item, params[:lost_status])
        iterator = iterator + 1
      end
    end
    @item.amount = @item.amount - params[:item][:amount].to_i
    if @item.amount == 0
      @item.destroy
    else
      @item.save
    end
    respond_to do |format|
      format.html { redirect_to backoffice_items_list_path, notice: 'Quantidade do item diminuida.'}
      format.js { }
    end
  end

  # GET /items_list
  def items_list
    @items = Item.all.order('updated_at DESC')
    respond_to do |format|
      format.html
      format.json { render json: ItemDatatable.new(params, view_context: view_context) }
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def create
    @item = Item.new(item_params)
    respond_to do |format|
      if @item.save
        format.html { redirect_to backoffice_items_path, notice: 'Item foi criado com sucesso.' }
        format.js { }
      else
        format.html { render :new, notice: "Ocorreu um erro. Por favor, preencha todos os campos do formulário." }
        format.js {  }
      end
    end
  end

  def update
    @item = Item.find(params[:id])

    respond_to do |format|
      if @item.update(item_params_edit)
        format.html { redirect_to backoffice_items_list_path, notice: "Item foi atualizado com sucesso." }
        format.js { }
      else
        format.html { render :edit, notice: "Ocorreu um erro. Por favor, preencha todos os campos do formulário." }
        format.js {  }
      end
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_items_path, notice: 'Doação deletada com sucesso.' }
      format.js {}
    end
  end

  private
  def addToSold(item)
    soldItem = SoldItem.new
    soldItem.name = item.name
    soldItem.code = item.id
    soldItem.value = item.value
    soldItem.amount = 1
    soldItem.save
  end

  def addToLost(item, status)
    lostItem = LostItem.new
    lostItem.name = item.name
    lostItem.code = item.id
    lostItem.value = item.value
    lostItem.status = status
    lostItem.save
  end

  def item_params
    params.require(:item).permit(:id, :name, :observation, :amount, :value,
                                 :donor, :receiver, :internal, :used, :lost,
                                 :used_product, :new_product)
  end
  def item_params_edit
    params.require(:item).permit(:id, :name, :observation, :amount, :value,
                                 :donor, :receiver, :internal, :used, :lost,
                                 :used_product, :new_product, :created_at)
  end
end

app/controllers/backoffice/lost_items_controller.rb
class Backoffice::LostItemsController < ApplicationController
  before_action :set_lost_item, only: [:show, :edit, :update, :destroy]

  # GET /lost_items
  # GET /lost_items.json
  def index
    @lost_items = LostItem.all.order('updated_at DESC')
    respond_to do |format|
      format.html
      format.json { render json: LostItemDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /lost_items/1
  # GET /lost_items/1.json
  def show
  end

  # GET /lost_items/new
  def new
    @lost_item = LostItem.new
  end

  # GET /lost_items/1/edit
  def edit
  end

  # POST /lost_items
  # POST /lost_items.json
  def create
    @lost_item = LostItem.new(lost_item_params)

    respond_to do |format|
      if @lost_item.save
        format.html { redirect_to @lost_item, notice: 'Lost item was successfully created.' }
        format.json { render :show, status: :created, location: @lost_item }
      else
        format.html { render :new }
        format.json { render json: @lost_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lost_items/1
  # PATCH/PUT /lost_items/1.json
  def update
    respond_to do |format|
      if @lost_item.update(lost_item_params)
        format.html { redirect_to @lost_item, notice: 'Lost item was successfully updated.' }
        format.json { render :show, status: :ok, location: @lost_item }
      else
        format.html { render :edit }
        format.json { render json: @lost_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lost_items/1
  # DELETE /lost_items/1.json
  def destroy
    @lost_item.destroy
    respond_to do |format|
      format.html { redirect_to lost_items_url, notice: 'Lost item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lost_item
      @lost_item = LostItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lost_item_params
      params.require(:lost_item).permit(:name, :code, :value, :status)
    end
end

app/controllers/backoffice/report_lists_controller.rb
# frozen_string_literal: true

class Backoffice::ReportListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_backoffice_report_list, only: [:edit, :update, :destroy]

  # GET /backoffice/report_lists
  # GET /backoffice/report_lists.json
  def index
    respond_to do |format|
      format.html
      format.json { render json: ReportListDatatable.new(params, view_context: view_context) }
    end
  end

  # GET /backoffice/report_lists/1
  # GET /backoffice/report_lists/1.json
  def show
    @backoffice_report_list = Backoffice::ReportList.find(params[:id])
    @lost_items = nil
    @sold_items = gather_data(@backoffice_report_list)
    @lost_items = gather_lost_item_data(@backoffice_report_list)
    @total_lost_value = 0.0
    @total_lost_amount = 0
    @total_value = 0
    @total_amount = 0
    @sold_items.each do |sold_item|
      @total_value += sold_item.value
      @total_amount += 1
    end
    @lost_items.each do |lost_item|
      @total_lost_value += lost_item.value
      @total_lost_amount += 1
    end
  end

  # GET /backoffice/report_lists/new
  def new
    @backoffice_report_list = Backoffice::ReportList.new
  end

  # GET /backoffice/report_lists/1/edit
  def edit
  end

  # POST /backoffice/report_lists
  # POST /backoffice/report_lists.json
  def create
    @backoffice_report_list = Backoffice::ReportList.new(backoffice_report_list_params)
    # formats date based on form income
    if params['backoffice_report_list']['today_only'] == "1"
      # @backoffice_report_list.from_date = Time.parse(Date.current.to_s).midnight
      # @backoffice_report_list.to_date = Time.parse(Date.current.to_s).end_of_day
      @backoffice_report_list.from_date = Date.current.to_s
      @backoffice_report_list.to_date = Date.current.to_s
    end
    respond_to do |format|
      if @backoffice_report_list.save
        format.html { redirect_to @backoffice_report_list, notice: 'Relatório de vendas criado com sucesso.' }
        format.json { render :show, status: :created, location: @backoffice_report_list }
      else
        format.html { render :new }
        format.json { render json: @backoffice_report_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backoffice/report_lists/1
  # PATCH/PUT /backoffice/report_lists/1.json
  def update
    respond_to do |format|
      if @backoffice_report_list.update(backoffice_report_list_params)
        format.html { redirect_to @backoffice_report_list, notice: 'Relatório de vendas editado com sucesso.' }
        format.json { render :show, status: :ok, location: @backoffice_report_list }
      else
        format.html { render :edit }
        format.json { render json: @backoffice_report_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backoffice/report_lists/1
  # DELETE /backoffice/report_lists/1.json
  def destroy
    @backoffice_report_list.destroy
    respond_to do |format|
      format.html { redirect_to backoffice_report_lists_url, notice: 'Relatório de vendas deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  # @param [Object] from
  def gather_data(report_list)
    from_date = Time.parse(report_list.from_date.to_s).midnight
    to_date = Time.parse(report_list.to_date.to_s).end_of_day
    sold_items = SoldItem.where("created_at >= ? AND created_at <= ?", from_date,
                                to_date)
    sold_items
  end

  def gather_lost_item_data(report_list)
    from_date = Time.parse(report_list.from_date.to_s).midnight
    to_date = Time.parse(report_list.to_date.to_s).end_of_day
    lost_items = LostItem.where("created_at >= ? AND created_at <= ?", from_date,
                                to_date)
    lost_items
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_backoffice_report_list
    @backoffice_report_list = Backoffice::ReportList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def backoffice_report_list_params
    params.require(:backoffice_report_list).permit(:name, :from_date, :to_date)
  end
end

app/helpers/backoffice/report_lists_helper.rb
module Backoffice::ReportListsHelper
end

app/helpers/backoffice/sold_items_helper.rb
module Backoffice::SoldItemsHelper
end

app/views/backoffice/report_lists/_form.html.erb
<%= form_with(model: backoffice_report_list, local: true) do |form| %>
  <% if backoffice_report_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(backoffice_report_list.errors.count, "erro") %> proibiram este relatório de ser criado:</h2>

      <ul>
        <% backoffice_report_list.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="row">
      <div class="col-6">
        <%= form.label :name, "Nome" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <div class="form-check">
        <%= form.check_box :today_only, id: "checkbox-today", class: "form-check-input" %>
        <label>Somente hoje</label>
      </div>
    </div>
  </div>

  <fieldset id="dates-fieldset">
    <div class="form-group">
      <div class="row">
        <div class="col-6">
          <%= form.label :from_date, "Do dia" %>
          <%= form.date_field :from_date, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <div class="row">
        <div class="col-6">
          <%= form.label :to_date, "Até o dia" %>
          <%= form.date_field :to_date, class: "form-control" %>
        </div>
      </div>
    </div>
  </fieldset>
  <div class="form-group">
    <div class="row">
      <div class="col-6">
        <%= form.submit "Salvar", class: 'btn btn-success' %>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $("#checkbox-today").click(function() {
            var isDisabled = $("#checkbox-today").prop('checked');
            if(!isDisabled) {
                $("#dates-fieldset").removeAttr("disabled");
            } else {
                $("#dates-fieldset").prop('disabled', true)
            }
        });
    });
</script>

app/views/backoffice/report_lists/edit.html.erb
<h1>Editing Backoffice Report List</h1>

<%= render 'form', backoffice_report_list: @backoffice_report_list %>

<%= link_to 'Show', @backoffice_report_list %> |
<%= link_to 'Back', backoffice_report_lists_path %>

app/views/backoffice/report_lists/index.html.erb
<div class="card">
  <div class="card-body">
    <div class="card-title">
      <h4>Relatórios de vendas do bazar</h4>
      <div class="table-responsive" style="overflow-y: auto;">
        <table class="table table-striped" id="dttb-backoffice_report_lists" data-sort="true" data-source="<%= backoffice_report_lists_path(format: :json)%>">
          <thead>
          <tr>
            <th data-data="name">Nome</th>
            <th data-data="from_date">Do dia</th>
            <th data-data="to_date">Até o dia</th>
            <th data-data="info">Informações</th>
            <th data-data="delete">Remover</th>
          </tr>
          </thead>

        </table>
      </div>
    </div>
  </div>
</div>

<br>

<%= link_to 'Novo relatório de vendas', new_backoffice_report_list_path, class: 'btn btn-success' %>


<script charset="utf-8">
    jQuery(document).ready(function() {
        $('#dttb-backoffice_report_lists').dataTable({
            "processing": true,
            "serverSide": true,
            "ajax": $('#dttb-backoffice_report_lists').data('source'),
            "pagingType": "full_numbers",
            "oLanguage": {
                "sEmptyTable": "Nenhum registro encontrado",
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "_MENU_ resultados por página",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sZeroRecords": "Nenhum registro encontrado",
                "sSearch": "Pesquisar",
                "oPaginate": {
                    "sNext": "Próximo",
                    "sPrevious": "Anterior",
                    "sFirst": "Primeiro",
                    "sLast": "Último"
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            },
            "columns": [
                {"data": "name"},
                {
                    "data": "from_date",
                    "type": "date"
                },
                {
                    "data": "to_date",
                    "type": "date"
                },
                {
                    "data": "information",
                    "bSortable": false,
                },
                {
                    "data": "delete",
                    "bSortable": false,
                }
            ]
        });
    });
</script>

app/views/backoffice/report_lists/new.html.erb
<h1>Criar novo relatório de vendas</h1>

<%= render 'form', backoffice_report_list: @backoffice_report_list %>

<%= link_to 'Voltar', backoffice_report_lists_path %>

app/views/backoffice/report_lists/show.html.erb
<div class="row purchace-popup">
  <div class="col-12">
    <span class="d-block d-md-flex align-items-center">
      <%= link_to "/backoffice/report_lists/new", class: "btn btn-success btn-lg btn-fw" do %>
        <i class="mdi mdi-plus-circle" style="color: white"></i>
        <span class="menu-title">Novo relatório de vendas</span>
      <% end %>
      <%= link_to "/backoffice/report_lists", class: "btn btn-primary btn-lg btn-fw" do %>
              <i class="mdi mdi-view-list" style="color: white"></i>
              <span class="menu-title">Listagem de relatórios</span>
            <% end %>
    </span>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="card-title">
      <h2><%= @backoffice_report_list.name %></h2>
      <h5>Do dia: <%= @backoffice_report_list.from_date.strftime("%d/%m/%Y") %></h5>
      <h5>Até dia: <%= @backoffice_report_list.to_date.strftime("%d/%m/%Y") %></h5>
    </div>
    <div class="card-title">
      <h2>Relatório de vendas</h2>
    </div>
    <div class="row">
      <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7 grid-margin stretch-card">
        <div class="card card-statistics">
          <div class="card-body">
            <h3>Valor total</h3>
            <p>
              <%= number_to_currency(@total_value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
            </p>
          </div>
        </div>
      </div>
      <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 grid-margin stretch-card">
        <div class="card card-statistics">
          <div class="card-body">
            <h3>Quantidade total</h3>
            <p>
              <%= @total_amount %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responive">
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Código</th>
          <th>Nome</th>
          <th>Valor</th>
        </tr>
        </thead>
        <tbody>
        <% @sold_items.each do |sold_item| %>
          <tr>
            <td><%= sold_item.code %></td>
            <td><%= sold_item.name %></td>
            <td>
              <%= number_to_currency(sold_item.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <div class="card-title">
      <h2>Relatório de perdas</h2>
    </div>
    <div class="row">
      <div class="col-xl-7 col-lg-7 col-md-7 col-sm-7 grid-margin stretch-card">
        <div class="card card-statistics">
          <div class="card-body">
            <h3>Valor total</h3>
            <p>
              <%= number_to_currency(@total_lost_value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
            </p>
          </div>
        </div>
      </div>
      <div class="col-xl-5 col-lg-5 col-md-5 col-sm-5 grid-margin stretch-card">
        <div class="card card-statistics">
          <div class="card-body">
            <h3>Quantidade total</h3>
            <p>
              <%= @total_lost_amount %>
            </p>
          </div>
        </div>
      </div>
    </div>
    <% if @lost_items %>
      <div class="table-responive">
        <table class="table table-striped">
          <thead>
          <tr>
            <th>Código</th>
            <th>Nome</th>
            <th>Valor</th>
          </tr>
          </thead>
          <tbody>
          <% @lost_items.each do |lost_item| %>
            <tr>
              <td><%= lost_item.code %></td>
              <td><%= lost_item.name %></td>
              <td>
                <%= number_to_currency(lost_item.value, :unit => "R$ ", :separator => ",", :delimiter => ".") %>
              </td>
            </tr>
          <% end %>

          </tbody>
        </table>
      </div>
    <% else %>
      <div></div>
    <% end %>
  </div>
</div>

<%= link_to 'Voltar', backoffice_report_lists_path %>